version: '3'

services:
  database:
    container_name: database
    image: postgres
    ports:
      - '5432:5432'
    restart: always  
    volumes:
      - /home/douglasfm/database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: postgres
